<?php

/**
 * Test class for GettextExtractor_Filters_AFilter.
 * Generated by PHPUnit on 2010-12-15 at 21:59:47.
 */
class GettextExtractor_Filters_AFilterTest extends PHPUnit_Framework_TestCase {

	/** @var AFilter */
	protected $object;

	protected function setUp() {
		$this->object = $this->getMockForAbstractClass('GettextExtractor_Filters_AFilter');
	}

	/**
	 * @expectedException InvalidArgumentException
	 * @dataProvider dataProvider_AddingFunctionWithInvalidParamter
	 */
	public function testAddingFunctionWithInvalidParamter($s, $p, $c) {
		$this->object->addFunction('function', $s, $p, $c);
	}
	public static function dataProvider_AddingFunctionWithInvalidParamter() {
		return array(
			array(0, null, null),
			array(1, 0, null),
			array(1, 2, 0),
			array('a', null, null),
			array(-2, null, null)
		);
	}

	public function testAddFunction() {
		$this->object->addFunction('function', 1, 2, 3);
	}
}
